### ISSUE TITLE
NPE

### ISSUE THREAD

**Issue by sah4ez** [CyberBiology/CyberBiology#3]
I got NullPointerException, stacktrace:
```
Exception in thread "Thread-1" java.lang.NullPointerException
	at java.io.File.<init>(File.java:277)
	at ru.cyberbiology.test.record.v0.RecordManager.save(RecordManager.java:51)
	at ru.cyberbiology.test.prototype.record.AbstractRecordManager$Worker.run(AbstractRecordManager.java:174)
Go to sleep, Frame set size = 51
Go to sleep, Frame set size = 51
Go to sleep, Frame set size = 51
Go to sleep, Frame set size = 51
```

**Comment by CyberBi** [comment]
fixed in new update
